### ISSUE TITLE
> 1. [ ]

### ISSUE THREAD

**Issue by Ahmedmohmmedz1** [skills/code-with-codespaces#126]
> 1. [ ]
> 
> * [ ]  استيراد CCXT استيراد الباندا كما PD وقت الاستيراد
> 
> # إعداد منصة التداول
> التبادل = ccxt.binance({ 'apiKey': 'YOUR_API_KEY', 'secret': 'YOUR_SECRET_KEY', })
> 
> # دالة لجلب بيانات السوق
> def fetch_data (الرمز ، الإطار الزمني = '1m' ، الحد = 100): الأشرطة = exchange.fetch_ohlcv (الرمز ، الإطار الزمني = الإطار الزمني ، الحد = الحد) df = PD. DataFrame (أشرطة ، أعمدة = ['طابع زمني' ، 'فتح' ، 'مرتفع' ، 'منخفض' ، 'إغلاق' ، 'حجم']) df ['الطابع الزمني'] = pd.to_datetime (df ['الطابع الزمني'] ، الوحدة = 'ms') إرجاع df
> 
> # دالة لاتخاذ قرار التداول
> def trading_decision(df): # استراتيجية بسيطة تعتمد على المتوسط المتحرك df['SMA'] = df['close'].rolling(window=20).mean() إذا كان df['close'].iloc[-1] > df['SMA'].iloc[-1]: إرجاع 'شراء' elif df['close'].iloc[-1] < df['SMA'].iloc[-1]: إرجاع 'بيع' آخر: إرجاع 'احتفاظ'
> 
> # دالة لتنفيذ التداول
> def execute_trade (الرمز ، القرار): إذا كان القرار == "شراء": الأمر = exchange.create_market_buy_order (الرمز ، 0.001) # شراء 0.001 بيتكوين قرار إليف == "بيع": الأمر = exchange.create_market_sell_order (الرمز ، 0.001) # بيع 0.001 بيتكوين طباعة (أمر)
> 
> # تشغيل الروبوت
> الرمز = "BTC / USDT" بينما True: df = fetch_data (رمز) القرار = trading_decision (df) execute_trade (الرمز ، القرار) time.sleep(60) # الانتظار لمدة دقيقة قبل التحقق مرة أخرى

_Originally posted by @Ahmedmohmmedz1 in https://github.com/skills/code-with-codespaces/issues/125#issuecomment-2515575496_

**Comment by TAO92996my** [comment]
What u mean..?
