### ISSUE TITLE
[Bug] Step 0 workflow not being triggered

### ISSUE THREAD

**Issue by RelicCornhusk** [skills/code-with-codespaces#87]
### Summary
When I create a repository from template by following the instructions on the README, the README does not update itself after refreshing the page after 20 seconds. In investigating the cause, I noticed that there was not execution for the Step 0 workflow in the 'Actions' tab. This is a consequence of the type of trigger being used (`create` instead of `push`).

I did notice one exception to this that is if the user selects the check box 'Include all branches', which also creates a branch besides 'main' during repository creation and thus runs the workflow. However, this checkbox is not selected by default and I suspect it would not trigger the automation if at any point there are no other branches besides 'main'.

### How to reproduce

1. Follow the steps on the README for creating repository from template.
2. Notice the README will not be changed after 20 seconds.

**Comment by hectorsector** [comment]
Thanks for the contribution, @RelicCornhusk! ❤ https://github.com/skills/code-with-codespaces/pull/86
